apiVersion: v1
kind: Service
metadata:
  name: srv-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30000
      protocol: TCP
  selector:
    app: node-svr
